stages:
  - build
  - staging
  - production


gradle-build:
  stage: build
  image : gradle:7.2-jdk11
  before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  script: ./gradlew --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

deploy_staging:
    type: deploy
    stage: staging
    image: ruby:latest
    script:
      - apt-get update -qy
      - apt-get install -y ruby-dev
      - gem install dpl
      - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
    only:
        - master

deploy_production:
    type: deploy
    stage: production
    image: ruby:latest
    script:
      - apt-get update -qy
      - apt-get install -y ruby-dev
      - gem install dpl      
      - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    when: manual
